#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile" ]; then
  . "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xprofile"
else
  . "$HOME"/.xprofile
fi

# Only when no display manager enabled
# while type dwm >/dev/null ; do dwm && continue || break ; done
