#!/bin/sh

# Check which window manager and execute utilities
[ $DESKTOP_SESSION == "dwm" ] && {
	xrandr --output DP-0 --mode 3440x1440 --rate 143.92
	picom &
	dunst &
	dwmblocks 2>&1 > /dev/null &
	nitrogen --restore
}
